### ISSUE TITLE
5g band support

### ISSUE THREAD

**Issue by sergeyksv** [kuba-moo/mt7630e#9]
Do you know if it is available?

**Comment by kuba-moo** [comment]
I don't think so. I guess only MediaTek could really answer this but as far as I understand their branding MTxx3x devices are 2.4GHz only and MTxx5x are dual-band. There supposedly (judging by [WikiDevi](https://wikidevi.com/wiki/Main_Page) and comments within the code) is a MT7650 design which supports 5GHz. I think the driver was written to serve more than one device, that's why there are references to 5GHz and all the channel defines. Perhaps the best way to check if your device supports 5GHz is to look at the specification of the laptop it was sold in. If nothing says 802.11ac then no 5GHz for you ;)

**Comment by sergeyksv** [comment]
Thanks for detailed explanation.
